name: Deploy to Cloud Run

on:
  workflow_dispatch:
  push:
    branches: [ release ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: whatsapp-assistant
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true
    
    - name: Configure Docker
      run: gcloud auth configure-docker
    
    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }} .
        docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }}
    
    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ${{ env.SERVICE_NAME }}
        image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
        region: ${{ env.REGION }}
        flags: '--memory=1Gi --cpu=1 --min-instances=1 --max-instances=1 --port=8080'
        env_vars: |
          LLM_PROVIDER=${{ secrets.LLM_PROVIDER }}
          LLM_MODEL=${{ secrets.LLM_MODEL }}
          LLM_API_BASE=${{ secrets.LLM_API_BASE }}
          LLM_API_KEY=${{ secrets.LLM_API_KEY }}
          CHAT_HISTORY_LIMIT=${{ secrets.CHAT_HISTORY_LIMIT || '20' }}
          PUPPETEER_ARGS=${{ secrets.PUPPETEER_ARGS || '--no-sandbox' }}
          MCP_SERVER_URL=${{ secrets.MCP_SERVER_URL || '' }}
        volumes: |
          name=data,mount_path=/app/data
          name=wwebjs-auth,mount_path=/app/.wwebjs_auth
    
    - name: Show deployed service URL
      run: echo "Service deployed to ${{ steps.deploy.outputs.url }}"
